services:
    api:
        container_name: "{{PROJECT_NAME}}_backend"
        build:
            context: ./backend
            target: dev
        ports:
            - "8000:80"
        volumes:
            - ./backend:/var/www/html
            - /var/www/html/vendor
        command: apache2-foreground
        env_file:
            - ./backend/.env
        depends_on:
            - db

    app:
        container_name: "{{PROJECT_NAME}}_frontend"
        build:
            context: ./frontend
            dockerfile: dockerfile
            target: dev
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules # Protéger node_modules
            - /app/.pnpm-store # Et protéger le cache pnpm
        command: pnpm run dev # Plus besoin de pnpm install !
        depends_on:
            - api

    db:
        image: mariadb:10.6
        container_name: "{{PROJECT_NAME}}_database"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: "{{DB_NAME}}"
            MYSQL_USER: "{{DB_USER}}"
            MYSQL_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - ./db_data:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "{{PROJECT_NAME}}_phpmyadmin"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - "8081:80"
        depends_on:
            - db
volumes:
    db_data:
